# Generated by Django 3.1.3 on 2020-11-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefcase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='galery'),
        ),
    ]
