# Generated by Django 3.1.3 on 2020-12-02 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("briefcase", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="url",
        ),
    ]
