# Generated by Django 3.1.3 on 2020-11-30 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_githubbutton'),
        ('briefcase', '0002_auto_20201129_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.basicinfo'),
            preserve_default=False,
        ),
    ]
