# Generated by Django 3.1.3 on 2020-12-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("briefcase", "0003_auto_20201203_1948"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="primary",
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
