# Generated by Django 3.1.3 on 2020-12-03 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("briefcase", "0004_image_primary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="image",
            new_name="images",
        ),
    ]
