# Generated by Django 3.1.3 on 2020-12-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefcase', '0005_auto_20201203_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='text_color',
            field=models.CharField(default='white', max_length=25),
        ),
    ]
