# Generated by Django 3.1.3 on 2020-12-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("briefcase", "0006_image_text_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="name",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
