# Generated by Django 3.1.3 on 2020-12-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("briefcase", "0007_auto_20201205_0734"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="name",
            field=models.CharField(blank=True, default=" ", max_length=25),
            preserve_default=False,
        ),
    ]
