# Generated by Django 3.1.3 on 2020-12-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("briefcase", "0009_auto_20201205_0800"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="position",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
