# Generated by Django 3.1.3 on 2020-12-05 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("briefcase", "0010_item_position"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="description",
        ),
    ]
