# Generated by Django 3.1.3 on 2020-11-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=45)),
                ('phone_numer', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=45)),
            ],
        ),
    ]
