# Generated by Django 3.1.3 on 2021-02-17 20:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BasicInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "info_id",
                    models.CharField(
                        blank=True, editable=False, max_length=32, null=True
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("address", models.CharField(max_length=45)),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.CharField(max_length=45)),
                ("extra_header", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="GraphItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("has_level", models.BooleanField(default=False)),
                (
                    "level",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("position", models.IntegerField(default=0)),
                (
                    "weight",
                    models.IntegerField(
                        default=400,
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(900),
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ListItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=90)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="This field supports bbcode https://en.wikipedia.org/wiki/BBCode",
                    ),
                ),
                ("year", models.CharField(blank=True, max_length=25)),
                ("position", models.IntegerField(default=0)),
                (
                    "weight",
                    models.IntegerField(
                        default=400,
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(900),
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UrlButton",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("url", models.CharField(max_length=60)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resume.basicinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SectionContent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="this field does not have anny effect on resume it is just a human readable name for an object",
                        max_length=20,
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        help_text="This field supports bbcode https://en.wikipedia.org/wiki/BBCode",
                    ),
                ),
                (
                    "graph_item",
                    models.ManyToManyField(blank=True, to="resume.GraphItem"),
                ),
                ("list_item", models.ManyToManyField(blank=True, to="resume.ListItem")),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("icon", models.CharField(max_length=20)),
                (
                    "section_type",
                    models.IntegerField(
                        choices=[(0, "Text"), (1, "List"), (2, "Graph")]
                    ),
                ),
                (
                    "position",
                    models.IntegerField(
                        default=0,
                        help_text="Determines position on resume, section with the smallest number will be on  the top",
                    ),
                ),
                (
                    "content",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resume.sectioncontent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resume.basicinfo",
                    ),
                ),
            ],
        ),
    ]
