# Generated by Django 3.1.3 on 2020-11-29 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicinfo',
            old_name='phone_numer',
            new_name='phone_number',
        ),
    ]
