# Generated by Django 3.1.3 on 2020-11-29 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20201129_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=20)),
                ('section_type', models.IntegerField(choices=[(0, 'Text'), (1, 'List'), (2, 'Graph')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.basicinfo')),
            ],
        ),
    ]
