# Generated by Django 3.1.3 on 2021-05-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20210510_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='image',
            field=models.CharField(help_text='Use emoji icons https://emojipedia.org/', max_length=4),
        ),
    ]
