# Generated by Django 3.1.3 on 2020-12-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0002_auto_20201202_1955"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listitem",
            name="headline",
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name="listitem",
            name="year",
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
