# Generated by Django 3.1.3 on 2020-12-08 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0003_auto_20201205_1401"),
    ]

    operations = [
        migrations.CreateModel(
            name="BasicInfoLink",
            fields=[],
            options={
                "verbose_name_plural": "Resumies list",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("resume.basicinfo",),
        ),
    ]
