# Generated by Django 3.1.3 on 2021-08-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20210822_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlbutton',
            name='user',
        ),
        migrations.AddField(
            model_name='urlbutton',
            name='user',
            field=models.ManyToManyField(to='resume.BasicInfo'),
        ),
    ]
