# Generated by Django 3.1.3 on 2021-01-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0004_basicinfolink"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BasicInfoLink",
        ),
        migrations.AddField(
            model_name="listitem",
            name="position",
            field=models.IntegerField(default=0),
        ),
    ]
