# Generated by Django 3.1.3 on 2020-11-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_item_sectioncontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectioncontent',
            name='item',
        ),
        migrations.AddField(
            model_name='sectioncontent',
            name='item',
            field=models.ManyToManyField(blank=True, to='resume.Item'),
        ),
    ]
