# Generated by Django 3.1.3 on 2021-02-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0005_auto_20210126_1120"),
    ]

    operations = [
        migrations.AddField(
            model_name="graphitem",
            name="has_level",
            field=models.BooleanField(default=False),
        ),
    ]
