# Generated by Django 3.1.3 on 2020-11-29 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20201129_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectioncontent',
            name='section',
        ),
        migrations.AddField(
            model_name='section',
            name='content',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.sectioncontent'),
            preserve_default=False,
        ),
    ]
