# Generated by Django 3.1.3 on 2021-08-23 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20210822_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.sectioncontent'),
        ),
    ]
