# Generated by Django 3.1.3 on 2021-08-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20210823_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='website',
            field=models.CharField(default='http://ww.w.google.pl', max_length=245),
            preserve_default=False,
        ),
    ]
