# Generated by Django 3.1.3 on 2021-02-14 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0006_graphitem_has_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graphitem",
            name="level",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
