# Generated by Django 3.1.3 on 2020-11-29 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_sectioncontent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resume.sectioncontent'),
        ),
    ]
