# Generated by Django 3.1.3 on 2021-02-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0007_auto_20210214_1755"),
    ]

    operations = [
        migrations.AddField(
            model_name="basicinfo",
            name="extra_header",
            field=models.TextField(blank=True, null=True),
        ),
    ]
