# Generated by Django 3.1.3 on 2021-10-01 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_basicinfo_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listitem',
            old_name='year',
            new_name='period',
        ),
    ]
