# Generated by Django 3.1.3 on 2021-02-14 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0008_basicinfo_extra_header"),
    ]

    operations = [
        migrations.CreateModel(
            name="UrlButton",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("url", models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name="basicinfo",
            name="extra_header",
            field=models.TextField(blank=True, default="GitHub"),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="GitHubButton",
        ),
        migrations.AddField(
            model_name="urlbutton",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="resume.basicinfo"
            ),
        ),
    ]
