# Generated by Django 3.1.3 on 2021-10-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_auto_20211001_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='short_description',
            field=models.TextField(blank=True, help_text='This field supports bbcode https://en.wikipedia.org/wiki/BBCode'),
        ),
    ]
