# Generated by Django 3.1.3 on 2020-11-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_auto_20201129_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectioncontent',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
