# Generated by Django 3.1.3 on 2021-10-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_listitem_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='cv_style',
            field=models.CharField(choices=[('st', 'standard'), ('hr', 'hacker')], default='hr', max_length=2),
            preserve_default=False,
        ),
    ]
