# Generated by Django 3.1.3 on 2021-02-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0009_auto_20210214_2006"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectioncontent",
            name="position",
            field=models.IntegerField(default=0),
        ),
    ]
