# Generated by Django 3.1.3 on 2020-11-29 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_auto_20201129_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.RenameModel(
            old_name='Item',
            new_name='ListItem',
        ),
        migrations.RemoveField(
            model_name='sectioncontent',
            name='item',
        ),
        migrations.AddField(
            model_name='sectioncontent',
            name='list_item',
            field=models.ManyToManyField(blank=True, to='resume.ListItem'),
        ),
        migrations.AddField(
            model_name='sectioncontent',
            name='graph_item',
            field=models.ManyToManyField(blank=True, to='resume.GraphItem'),
        ),
    ]
