# Generated by Django 3.1.3 on 2021-02-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0010_sectioncontent_position"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sectioncontent",
            name="position",
        ),
        migrations.AddField(
            model_name="graphitem",
            name="position",
            field=models.IntegerField(default=0),
        ),
    ]
