# Generated by Django 3.1.3 on 2020-11-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_auto_20201129_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='position',
            field=models.IntegerField(default=0, help_text='Determines position on resume, section with the smallest number will be on  the top'),
        ),
    ]
