# Generated by Django 3.1.3 on 2021-02-14 22:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0011_auto_20210214_2125"),
    ]

    operations = [
        migrations.AddField(
            model_name="graphitem",
            name="weight",
            field=models.IntegerField(
                default=400,
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(900),
                ],
            ),
        ),
        migrations.AddField(
            model_name="listitem",
            name="weight",
            field=models.IntegerField(
                default=400,
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(900),
                ],
            ),
        ),
    ]
