# Generated by Django 3.1.3 on 2021-02-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0012_auto_20210214_2226"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listitem",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="This field supports bbcode https://en.wikipedia.org/wiki/BBCode",
            ),
        ),
    ]
