# Generated by Django 3.1.3 on 2021-10-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_listitem_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphitem',
            name='level_desc',
            field=models.CharField(blank=True, help_text='This is a text description of the proficiency level', max_length=25),
        ),
    ]
