# Generated by Django 3.1.3 on 2020-11-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_section_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='info_id',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True),
        ),
    ]
