# Generated by Django 3.1.3 on 2021-10-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_graphitem_level_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='max_height',
            field=models.SmallIntegerField(help_text='Height of the section, scrolbar if overflows', null=True),
        ),
    ]
