# Generated by Django 3.1.3 on 2020-11-30 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_basicinfo_info_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.basicinfo')),
            ],
        ),
    ]
