# Generated by Django 3.1.3 on 2022-01-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_section_max_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
