# Generated by Django 3.1.3 on 2022-01-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_basicinfo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='code',
            field=models.CharField(default='es', max_length=10),
            preserve_default=False,
        ),
    ]
