# Generated by Django 3.1.3 on 2022-05-14 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='mobile_version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.basicinfo'),
            preserve_default=False,
        ),
    ]
