# Generated by Django 3.1.3 on 2022-05-14 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0017_basicinfo_mobile_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='mobile_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.basicinfo'),
        ),
    ]
