# Generated by Django 3.1.3 on 2022-05-14 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0018_auto_20220514_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='mobile_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.basicinfo'),
        ),
    ]
